// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetDevices implements getDevices operation.
//
// Performs live SSDP discovery and returns currently available devices on the local network.
//
// GET /api/devices
func (UnimplementedHandler) GetDevices(ctx context.Context) (r GetDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartAnimation implements startAnimation operation.
//
// Starts playing an animation loop on the specified device. Only one animation can run per device at
// a time.
//
// POST /animation/start
func (UnimplementedHandler) StartAnimation(ctx context.Context, req *StartAnimationRequest) (r StartAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StopAnimation implements stopAnimation operation.
//
// Stops the currently running animation on the specified device. No-op if no animation is running.
//
// POST /animation/stop
func (UnimplementedHandler) StopAnimation(ctx context.Context, req *StopAnimationRequest) (r StopAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}
