// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

type AnimationFrame []RGBPixel

type DeleteAnimationInternalServerError Error

func (*DeleteAnimationInternalServerError) deleteAnimationRes() {}

type DeleteAnimationNotFound Error

func (*DeleteAnimationNotFound) deleteAnimationRes() {}

// Ref: #/components/schemas/DeleteAnimationResponse
type DeleteAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *DeleteAnimationResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *DeleteAnimationResponse) SetMessage(val string) {
	s.Message = val
}

func (*DeleteAnimationResponse) deleteAnimationRes() {}

// Ref: #/components/schemas/Device
type Device struct {
	// Unique device identifier.
	ID string `json:"id"`
	// Human-readable device name.
	Name string `json:"name"`
	// Device location in format yeelight://IP:PORT.
	Location string `json:"location"`
}

// GetID returns the value of ID.
func (s *Device) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Device) GetName() string {
	return s.Name
}

// GetLocation returns the value of Location.
func (s *Device) GetLocation() string {
	return s.Location
}

// SetID sets the value of ID.
func (s *Device) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Device) SetName(val string) {
	s.Name = val
}

// SetLocation sets the value of Location.
func (s *Device) SetLocation(val string) {
	s.Location = val
}

// Ref: #/components/schemas/Error
type Error struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) getDevicesRes()     {}
func (*Error) listAnimationsRes() {}

type GetAnimationInternalServerError Error

func (*GetAnimationInternalServerError) getAnimationRes() {}

type GetAnimationNotFound Error

func (*GetAnimationNotFound) getAnimationRes() {}

// Ref: #/components/schemas/GetAnimationResponse
type GetAnimationResponse struct {
	Animation SavedAnimation `json:"animation"`
}

// GetAnimation returns the value of Animation.
func (s *GetAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetAnimation sets the value of Animation.
func (s *GetAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*GetAnimationResponse) getAnimationRes() {}

type GetDevicesOK struct {
	Devices []Device `json:"devices"`
}

// GetDevices returns the value of Devices.
func (s *GetDevicesOK) GetDevices() []Device {
	return s.Devices
}

// SetDevices sets the value of Devices.
func (s *GetDevicesOK) SetDevices(val []Device) {
	s.Devices = val
}

func (*GetDevicesOK) getDevicesRes() {}

// Ref: #/components/schemas/ListAnimationsResponse
type ListAnimationsResponse struct {
	// List of saved animations for the device, ordered by updated_at descending.
	Animations []SavedAnimation `json:"animations"`
}

// GetAnimations returns the value of Animations.
func (s *ListAnimationsResponse) GetAnimations() []SavedAnimation {
	return s.Animations
}

// SetAnimations sets the value of Animations.
func (s *ListAnimationsResponse) SetAnimations(val []SavedAnimation) {
	s.Animations = val
}

func (*ListAnimationsResponse) listAnimationsRes() {}

// Ref: #/components/schemas/RGBPixel
type RGBPixel struct {
	// Red component (0-255).
	R int32 `json:"r"`
	// Green component (0-255).
	G int32 `json:"g"`
	// Blue component (0-255).
	B int32 `json:"b"`
}

// GetR returns the value of R.
func (s *RGBPixel) GetR() int32 {
	return s.R
}

// GetG returns the value of G.
func (s *RGBPixel) GetG() int32 {
	return s.G
}

// GetB returns the value of B.
func (s *RGBPixel) GetB() int32 {
	return s.B
}

// SetR sets the value of R.
func (s *RGBPixel) SetR(val int32) {
	s.R = val
}

// SetG sets the value of G.
func (s *RGBPixel) SetG(val int32) {
	s.G = val
}

// SetB sets the value of B.
func (s *RGBPixel) SetB(val int32) {
	s.B = val
}

type SaveAnimationBadRequest Error

func (*SaveAnimationBadRequest) saveAnimationRes() {}

type SaveAnimationInternalServerError Error

func (*SaveAnimationInternalServerError) saveAnimationRes() {}

// Ref: #/components/schemas/SaveAnimationRequest
type SaveAnimationRequest struct {
	// Device location to save animation for.
	DeviceID string `json:"device_id"`
	// Name for the animation.
	Name string `json:"name"`
	// Array of animation frames to save.
	Frames []AnimationFrame `json:"frames"`
}

// GetDeviceID returns the value of DeviceID.
func (s *SaveAnimationRequest) GetDeviceID() string {
	return s.DeviceID
}

// GetName returns the value of Name.
func (s *SaveAnimationRequest) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *SaveAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetDeviceID sets the value of DeviceID.
func (s *SaveAnimationRequest) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetName sets the value of Name.
func (s *SaveAnimationRequest) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *SaveAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/SaveAnimationResponse
type SaveAnimationResponse struct {
	// UUID of the newly saved animation.
	ID string `json:"id"`
	// Success message.
	Message   string         `json:"message"`
	Animation SavedAnimation `json:"animation"`
}

// GetID returns the value of ID.
func (s *SaveAnimationResponse) GetID() string {
	return s.ID
}

// GetMessage returns the value of Message.
func (s *SaveAnimationResponse) GetMessage() string {
	return s.Message
}

// GetAnimation returns the value of Animation.
func (s *SaveAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetID sets the value of ID.
func (s *SaveAnimationResponse) SetID(val string) {
	s.ID = val
}

// SetMessage sets the value of Message.
func (s *SaveAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetAnimation sets the value of Animation.
func (s *SaveAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*SaveAnimationResponse) saveAnimationRes() {}

// Ref: #/components/schemas/SavedAnimation
type SavedAnimation struct {
	// Unique animation identifier.
	ID string `json:"id"`
	// Device location this animation is saved for.
	DeviceID string `json:"device_id"`
	// User-provided name for the animation.
	Name string `json:"name"`
	// Array of animation frames.
	Frames []AnimationFrame `json:"frames"`
	// Timestamp when animation was created.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp when animation was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *SavedAnimation) GetID() string {
	return s.ID
}

// GetDeviceID returns the value of DeviceID.
func (s *SavedAnimation) GetDeviceID() string {
	return s.DeviceID
}

// GetName returns the value of Name.
func (s *SavedAnimation) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *SavedAnimation) GetFrames() []AnimationFrame {
	return s.Frames
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SavedAnimation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SavedAnimation) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SavedAnimation) SetID(val string) {
	s.ID = val
}

// SetDeviceID sets the value of DeviceID.
func (s *SavedAnimation) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetName sets the value of Name.
func (s *SavedAnimation) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *SavedAnimation) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SavedAnimation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SavedAnimation) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

type StartAnimationBadRequest Error

func (*StartAnimationBadRequest) startAnimationRes() {}

type StartAnimationInternalServerError Error

func (*StartAnimationInternalServerError) startAnimationRes() {}

// Ref: #/components/schemas/StartAnimationRequest
type StartAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
	// Array of animation frames to play in sequence.
	Frames []AnimationFrame `json:"frames"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StartAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// GetFrames returns the value of Frames.
func (s *StartAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StartAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// SetFrames sets the value of Frames.
func (s *StartAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/StartAnimationResponse
type StartAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
	// Number of frames in the animation.
	FrameCount int `json:"frame_count"`
}

// GetMessage returns the value of Message.
func (s *StartAnimationResponse) GetMessage() string {
	return s.Message
}

// GetFrameCount returns the value of FrameCount.
func (s *StartAnimationResponse) GetFrameCount() int {
	return s.FrameCount
}

// SetMessage sets the value of Message.
func (s *StartAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetFrameCount sets the value of FrameCount.
func (s *StartAnimationResponse) SetFrameCount(val int) {
	s.FrameCount = val
}

func (*StartAnimationResponse) startAnimationRes() {}

type StopAnimationBadRequest Error

func (*StopAnimationBadRequest) stopAnimationRes() {}

type StopAnimationInternalServerError Error

func (*StopAnimationInternalServerError) stopAnimationRes() {}

// Ref: #/components/schemas/StopAnimationRequest
type StopAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StopAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StopAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// Ref: #/components/schemas/StopAnimationResponse
type StopAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *StopAnimationResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *StopAnimationResponse) SetMessage(val string) {
	s.Message = val
}

func (*StopAnimationResponse) stopAnimationRes() {}

type UpdateAnimationBadRequest Error

func (*UpdateAnimationBadRequest) updateAnimationRes() {}

type UpdateAnimationInternalServerError Error

func (*UpdateAnimationInternalServerError) updateAnimationRes() {}

type UpdateAnimationNotFound Error

func (*UpdateAnimationNotFound) updateAnimationRes() {}

// Ref: #/components/schemas/UpdateAnimationRequest
type UpdateAnimationRequest struct {
	// Updated name for the animation.
	Name string `json:"name"`
	// Updated animation frames.
	Frames []AnimationFrame `json:"frames"`
}

// GetName returns the value of Name.
func (s *UpdateAnimationRequest) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *UpdateAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetName sets the value of Name.
func (s *UpdateAnimationRequest) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *UpdateAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/UpdateAnimationResponse
type UpdateAnimationResponse struct {
	// Success message.
	Message   string         `json:"message"`
	Animation SavedAnimation `json:"animation"`
}

// GetMessage returns the value of Message.
func (s *UpdateAnimationResponse) GetMessage() string {
	return s.Message
}

// GetAnimation returns the value of Animation.
func (s *UpdateAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetMessage sets the value of Message.
func (s *UpdateAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetAnimation sets the value of Animation.
func (s *UpdateAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*UpdateAnimationResponse) updateAnimationRes() {}
