// Code generated by ogen, DO NOT EDIT.

package api

type AnimationFrame []RGBPixel

// Ref: #/components/schemas/Device
type Device struct {
	// Unique device identifier.
	ID string `json:"id"`
	// Human-readable device name.
	Name string `json:"name"`
	// Device location in format yeelight://IP:PORT.
	Location string `json:"location"`
}

// GetID returns the value of ID.
func (s *Device) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Device) GetName() string {
	return s.Name
}

// GetLocation returns the value of Location.
func (s *Device) GetLocation() string {
	return s.Location
}

// SetID sets the value of ID.
func (s *Device) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Device) SetName(val string) {
	s.Name = val
}

// SetLocation sets the value of Location.
func (s *Device) SetLocation(val string) {
	s.Location = val
}

// Ref: #/components/schemas/Error
type Error struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) getDevicesRes() {}

type GetDevicesOK struct {
	Devices []Device `json:"devices"`
}

// GetDevices returns the value of Devices.
func (s *GetDevicesOK) GetDevices() []Device {
	return s.Devices
}

// SetDevices sets the value of Devices.
func (s *GetDevicesOK) SetDevices(val []Device) {
	s.Devices = val
}

func (*GetDevicesOK) getDevicesRes() {}

// Ref: #/components/schemas/RGBPixel
type RGBPixel struct {
	// Red component (0-255).
	R int32 `json:"r"`
	// Green component (0-255).
	G int32 `json:"g"`
	// Blue component (0-255).
	B int32 `json:"b"`
}

// GetR returns the value of R.
func (s *RGBPixel) GetR() int32 {
	return s.R
}

// GetG returns the value of G.
func (s *RGBPixel) GetG() int32 {
	return s.G
}

// GetB returns the value of B.
func (s *RGBPixel) GetB() int32 {
	return s.B
}

// SetR sets the value of R.
func (s *RGBPixel) SetR(val int32) {
	s.R = val
}

// SetG sets the value of G.
func (s *RGBPixel) SetG(val int32) {
	s.G = val
}

// SetB sets the value of B.
func (s *RGBPixel) SetB(val int32) {
	s.B = val
}

type StartAnimationBadRequest Error

func (*StartAnimationBadRequest) startAnimationRes() {}

type StartAnimationInternalServerError Error

func (*StartAnimationInternalServerError) startAnimationRes() {}

// Ref: #/components/schemas/StartAnimationRequest
type StartAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
	// Array of animation frames to play in sequence.
	Frames []AnimationFrame `json:"frames"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StartAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// GetFrames returns the value of Frames.
func (s *StartAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StartAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// SetFrames sets the value of Frames.
func (s *StartAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/StartAnimationResponse
type StartAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
	// Number of frames in the animation.
	FrameCount int `json:"frame_count"`
}

// GetMessage returns the value of Message.
func (s *StartAnimationResponse) GetMessage() string {
	return s.Message
}

// GetFrameCount returns the value of FrameCount.
func (s *StartAnimationResponse) GetFrameCount() int {
	return s.FrameCount
}

// SetMessage sets the value of Message.
func (s *StartAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetFrameCount sets the value of FrameCount.
func (s *StartAnimationResponse) SetFrameCount(val int) {
	s.FrameCount = val
}

func (*StartAnimationResponse) startAnimationRes() {}

type StopAnimationBadRequest Error

func (*StopAnimationBadRequest) stopAnimationRes() {}

type StopAnimationInternalServerError Error

func (*StopAnimationInternalServerError) stopAnimationRes() {}

// Ref: #/components/schemas/StopAnimationRequest
type StopAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StopAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StopAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// Ref: #/components/schemas/StopAnimationResponse
type StopAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *StopAnimationResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *StopAnimationResponse) SetMessage(val string) {
	s.Message = val
}

func (*StopAnimationResponse) stopAnimationRes() {}
