// Code generated by ogen, DO NOT EDIT.
package api

type GetDevicesRes interface {
	getDevicesRes()
}

type StartAnimationRes interface {
	startAnimationRes()
}

type StopAnimationRes interface {
	stopAnimationRes()
}
