// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteAnimation implements deleteAnimation operation.
//
// Permanently removes a saved animation from the database.
//
// DELETE /api/animation/{id}
func (UnimplementedHandler) DeleteAnimation(ctx context.Context, params DeleteAnimationParams) (r DeleteAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAnimation implements getAnimation operation.
//
// Retrieves a saved animation by its ID.
//
// GET /api/animation/{id}
func (UnimplementedHandler) GetAnimation(ctx context.Context, params GetAnimationParams) (r GetAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDevices implements getDevices operation.
//
// Performs live SSDP discovery and returns currently available devices on the local network.
//
// GET /api/devices
func (UnimplementedHandler) GetDevices(ctx context.Context) (r GetDevicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAnimations implements listAnimations operation.
//
// Returns all saved animations for the specified device, ordered by most recently updated.
//
// GET /api/animation/list/{device_id}
func (UnimplementedHandler) ListAnimations(ctx context.Context, params ListAnimationsParams) (r ListAnimationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveAnimation implements saveAnimation operation.
//
// Saves the current animation frames to the database with a name. Stored per device.
//
// POST /api/animation/save
func (UnimplementedHandler) SaveAnimation(ctx context.Context, req *SaveAnimationRequest) (r SaveAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartAnimation implements startAnimation operation.
//
// Starts playing an animation loop on the specified device. Only one animation can run per device at
// a time.
//
// POST /api/animation/start
func (UnimplementedHandler) StartAnimation(ctx context.Context, req *StartAnimationRequest) (r StartAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StopAnimation implements stopAnimation operation.
//
// Stops the currently running animation on the specified device. No-op if no animation is running.
//
// POST /api/animation/stop
func (UnimplementedHandler) StopAnimation(ctx context.Context, req *StopAnimationRequest) (r StopAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAnimation implements updateAnimation operation.
//
// Overwrites an existing animation's name and frames.
//
// PUT /api/animation/{id}
func (UnimplementedHandler) UpdateAnimation(ctx context.Context, req *UpdateAnimationRequest, params UpdateAnimationParams) (r UpdateAnimationRes, _ error) {
	return r, ht.ErrNotImplemented
}
