// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteAnimationOperation OperationName = "DeleteAnimation"
	GetAnimationOperation    OperationName = "GetAnimation"
	GetDevicesOperation      OperationName = "GetDevices"
	ListAnimationsOperation  OperationName = "ListAnimations"
	PowerOffOperation        OperationName = "PowerOff"
	PowerOnOperation         OperationName = "PowerOn"
	SaveAnimationOperation   OperationName = "SaveAnimation"
	StartAnimationOperation  OperationName = "StartAnimation"
	StopAnimationOperation   OperationName = "StopAnimation"
	UpdateAnimationOperation OperationName = "UpdateAnimation"
)
