// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DeleteAnimation implements deleteAnimation operation.
	//
	// Permanently removes a saved animation from the database.
	//
	// DELETE /api/animation/{id}
	DeleteAnimation(ctx context.Context, params DeleteAnimationParams) (DeleteAnimationRes, error)
	// ExportAnimation implements exportAnimation operation.
	//
	// Fetches the saved animation and returns a versioned Sparse JSON representation suitable for sharing
	// across devices and users. The response carries a Content-Disposition attachment header so browsers
	// treat it as a downloadable file. Note: the Content-Disposition header is set by the Go HTTP layer,
	// not by ogen; the spec documents it for clients but does not drive code generation for it.
	//
	// GET /api/animation/{id}/export
	ExportAnimation(ctx context.Context, params ExportAnimationParams) (ExportAnimationRes, error)
	// GetAnimation implements getAnimation operation.
	//
	// Retrieves a saved animation by its ID.
	//
	// GET /api/animation/{id}
	GetAnimation(ctx context.Context, params GetAnimationParams) (GetAnimationRes, error)
	// GetDevices implements getDevices operation.
	//
	// Performs live SSDP discovery and returns currently available devices on the local network.
	//
	// GET /api/devices
	GetDevices(ctx context.Context) (GetDevicesRes, error)
	// ImportAnimation implements importAnimation operation.
	//
	// Accepts a Sparse JSON animation payload (with target device id) and persists it. Validation runs
	// first; on success the codec persists via the configured conflict-resolution mode.
	//
	// POST /api/animation/import
	ImportAnimation(ctx context.Context, req *ImportAnimationRequest, params ImportAnimationParams) (ImportAnimationRes, error)
	// ListAnimations implements listAnimations operation.
	//
	// Returns all saved animations for the specified device, ordered by most recently updated.
	//
	// GET /api/animation/list/{device_id}
	ListAnimations(ctx context.Context, params ListAnimationsParams) (ListAnimationsRes, error)
	// PowerOff implements powerOff operation.
	//
	// Turns off the specified Yeelight device with a smooth transition effect.
	//
	// POST /api/device/power/off
	PowerOff(ctx context.Context, req *PowerOffRequest) (PowerOffRes, error)
	// PowerOn implements powerOn operation.
	//
	// Turns on the specified Yeelight device with a smooth transition effect.
	//
	// POST /api/device/power/on
	PowerOn(ctx context.Context, req *PowerOnRequest) (PowerOnRes, error)
	// SaveAnimation implements saveAnimation operation.
	//
	// Saves the current animation frames to the database with a name. Stored per device.
	//
	// POST /api/animation/save
	SaveAnimation(ctx context.Context, req *SaveAnimationRequest) (SaveAnimationRes, error)
	// StartAnimation implements startAnimation operation.
	//
	// Starts playing an animation loop on the specified device. Only one animation can run per device at a
	// time.
	//
	// POST /api/animation/start
	StartAnimation(ctx context.Context, req *StartAnimationRequest) (StartAnimationRes, error)
	// StopAnimation implements stopAnimation operation.
	//
	// Stops the currently running animation on the specified device. No-op if no animation is running.
	//
	// POST /api/animation/stop
	StopAnimation(ctx context.Context, req *StopAnimationRequest) (StopAnimationRes, error)
	// UpdateAnimation implements updateAnimation operation.
	//
	// Overwrites an existing animation's name and frames.
	//
	// PUT /api/animation/{id}
	UpdateAnimation(ctx context.Context, req *UpdateAnimationRequest, params UpdateAnimationParams) (UpdateAnimationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
