// Code generated by ogen, DO NOT EDIT.
package api

type DeleteAnimationRes interface {
	deleteAnimationRes()
}

type ExportAnimationRes interface {
	exportAnimationRes()
}

type GetAnimationRes interface {
	getAnimationRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}

type ImportAnimationRes interface {
	importAnimationRes()
}

type ListAnimationsRes interface {
	listAnimationsRes()
}

type PowerOffRes interface {
	powerOffRes()
}

type PowerOnRes interface {
	powerOnRes()
}

type SaveAnimationRes interface {
	saveAnimationRes()
}

type StartAnimationRes interface {
	startAnimationRes()
}

type StopAnimationRes interface {
	stopAnimationRes()
}

type UpdateAnimationRes interface {
	updateAnimationRes()
}
