// Code generated by ogen, DO NOT EDIT.
package api

type DeleteAnimationRes interface {
	deleteAnimationRes()
}

type GetAnimationRes interface {
	getAnimationRes()
}

type GetDevicesRes interface {
	getDevicesRes()
}

type ListAnimationsRes interface {
	listAnimationsRes()
}

type SaveAnimationRes interface {
	saveAnimationRes()
}

type StartAnimationRes interface {
	startAnimationRes()
}

type StopAnimationRes interface {
	stopAnimationRes()
}

type UpdateAnimationRes interface {
	updateAnimationRes()
}
