// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetDevices implements getDevices operation.
	//
	// Performs live SSDP discovery and returns currently available devices on the local network.
	//
	// GET /api/devices
	GetDevices(ctx context.Context) (GetDevicesRes, error)
	// StartAnimation implements startAnimation operation.
	//
	// Starts playing an animation loop on the specified device. Only one animation can run per device at
	// a time.
	//
	// POST /animation/start
	StartAnimation(ctx context.Context, req *StartAnimationRequest) (StartAnimationRes, error)
	// StopAnimation implements stopAnimation operation.
	//
	// Stops the currently running animation on the specified device. No-op if no animation is running.
	//
	// POST /animation/stop
	StopAnimation(ctx context.Context, req *StopAnimationRequest) (StopAnimationRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
