// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type AnimationFrame []RGBPixel

type DeleteAnimationInternalServerError Error

func (*DeleteAnimationInternalServerError) deleteAnimationRes() {}

type DeleteAnimationNotFound Error

func (*DeleteAnimationNotFound) deleteAnimationRes() {}

// Ref: #/components/schemas/DeleteAnimationResponse
type DeleteAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *DeleteAnimationResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *DeleteAnimationResponse) SetMessage(val string) {
	s.Message = val
}

func (*DeleteAnimationResponse) deleteAnimationRes() {}

// Ref: #/components/schemas/Device
type Device struct {
	// Unique device identifier.
	ID string `json:"id"`
	// Human-readable device name.
	Name string `json:"name"`
	// Device location in format yeelight://IP:PORT.
	Location string `json:"location"`
	// Power state as last set through this backend; unknown after a backend restart (the CubeLite can't be
	// queried).
	Power DevicePower `json:"power"`
	// Animation currently looping on the device, or null when nothing is playing.
	Playback OptNilPlayback `json:"playback"`
}

// GetID returns the value of ID.
func (s *Device) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *Device) GetName() string {
	return s.Name
}

// GetLocation returns the value of Location.
func (s *Device) GetLocation() string {
	return s.Location
}

// GetPower returns the value of Power.
func (s *Device) GetPower() DevicePower {
	return s.Power
}

// GetPlayback returns the value of Playback.
func (s *Device) GetPlayback() OptNilPlayback {
	return s.Playback
}

// SetID sets the value of ID.
func (s *Device) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Device) SetName(val string) {
	s.Name = val
}

// SetLocation sets the value of Location.
func (s *Device) SetLocation(val string) {
	s.Location = val
}

// SetPower sets the value of Power.
func (s *Device) SetPower(val DevicePower) {
	s.Power = val
}

// SetPlayback sets the value of Playback.
func (s *Device) SetPlayback(val OptNilPlayback) {
	s.Playback = val
}

// Power state as last set through this backend; unknown after a backend restart (the CubeLite can't be
// queried).
type DevicePower string

const (
	DevicePowerOn      DevicePower = "on"
	DevicePowerOff     DevicePower = "off"
	DevicePowerUnknown DevicePower = "unknown"
)

// AllValues returns all DevicePower values.
func (DevicePower) AllValues() []DevicePower {
	return []DevicePower{
		DevicePowerOn,
		DevicePowerOff,
		DevicePowerUnknown,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DevicePower) MarshalText() ([]byte, error) {
	switch s {
	case DevicePowerOn:
		return []byte(s), nil
	case DevicePowerOff:
		return []byte(s), nil
	case DevicePowerUnknown:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DevicePower) UnmarshalText(data []byte) error {
	switch DevicePower(data) {
	case DevicePowerOn:
		*s = DevicePowerOn
		return nil
	case DevicePowerOff:
		*s = DevicePowerOff
		return nil
	case DevicePowerUnknown:
		*s = DevicePowerUnknown
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Error
type Error struct {
	// Error message.
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) getDevicesRes()     {}
func (*Error) listAnimationsRes() {}

type ExportAnimationInternalServerError Error

func (*ExportAnimationInternalServerError) exportAnimationRes() {}

type ExportAnimationNotFound Error

func (*ExportAnimationNotFound) exportAnimationRes() {}

type GetAnimationInternalServerError Error

func (*GetAnimationInternalServerError) getAnimationRes() {}

type GetAnimationNotFound Error

func (*GetAnimationNotFound) getAnimationRes() {}

// Ref: #/components/schemas/GetAnimationResponse
type GetAnimationResponse struct {
	Animation SavedAnimation `json:"animation"`
}

// GetAnimation returns the value of Animation.
func (s *GetAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetAnimation sets the value of Animation.
func (s *GetAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*GetAnimationResponse) getAnimationRes() {}

type GetDevicesOK struct {
	Devices []Device `json:"devices"`
}

// GetDevices returns the value of Devices.
func (s *GetDevicesOK) GetDevices() []Device {
	return s.Devices
}

// SetDevices sets the value of Devices.
func (s *GetDevicesOK) SetDevices(val []Device) {
	s.Devices = val
}

func (*GetDevicesOK) getDevicesRes() {}

type ImportAnimationInternalServerError Error

func (*ImportAnimationInternalServerError) importAnimationRes() {}

type ImportAnimationMode string

const (
	ImportAnimationModeRename    ImportAnimationMode = "rename"
	ImportAnimationModeOverwrite ImportAnimationMode = "overwrite"
	ImportAnimationModeCancel    ImportAnimationMode = "cancel"
)

// AllValues returns all ImportAnimationMode values.
func (ImportAnimationMode) AllValues() []ImportAnimationMode {
	return []ImportAnimationMode{
		ImportAnimationModeRename,
		ImportAnimationModeOverwrite,
		ImportAnimationModeCancel,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ImportAnimationMode) MarshalText() ([]byte, error) {
	switch s {
	case ImportAnimationModeRename:
		return []byte(s), nil
	case ImportAnimationModeOverwrite:
		return []byte(s), nil
	case ImportAnimationModeCancel:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ImportAnimationMode) UnmarshalText(data []byte) error {
	switch ImportAnimationMode(data) {
	case ImportAnimationModeRename:
		*s = ImportAnimationModeRename
		return nil
	case ImportAnimationModeOverwrite:
		*s = ImportAnimationModeOverwrite
		return nil
	case ImportAnimationModeCancel:
		*s = ImportAnimationModeCancel
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ImportAnimationRequest
type ImportAnimationRequest struct {
	// Target device for the imported animation.
	DeviceID  string          `json:"device_id"`
	Animation SparseAnimation `json:"animation"`
}

// GetDeviceID returns the value of DeviceID.
func (s *ImportAnimationRequest) GetDeviceID() string {
	return s.DeviceID
}

// GetAnimation returns the value of Animation.
func (s *ImportAnimationRequest) GetAnimation() SparseAnimation {
	return s.Animation
}

// SetDeviceID sets the value of DeviceID.
func (s *ImportAnimationRequest) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetAnimation sets the value of Animation.
func (s *ImportAnimationRequest) SetAnimation(val SparseAnimation) {
	s.Animation = val
}

type ImportAnimationRequestEntityTooLarge Error

func (*ImportAnimationRequestEntityTooLarge) importAnimationRes() {}

// Ref: #/components/schemas/ImportAnimationResponse
type ImportAnimationResponse struct {
	Animation SavedAnimation `json:"animation"`
	// Original name when the server renamed to avoid a collision; absent when no rename occurred.
	RenamedFrom OptString `json:"renamed_from"`
}

// GetAnimation returns the value of Animation.
func (s *ImportAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// GetRenamedFrom returns the value of RenamedFrom.
func (s *ImportAnimationResponse) GetRenamedFrom() OptString {
	return s.RenamedFrom
}

// SetAnimation sets the value of Animation.
func (s *ImportAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

// SetRenamedFrom sets the value of RenamedFrom.
func (s *ImportAnimationResponse) SetRenamedFrom(val OptString) {
	s.RenamedFrom = val
}

func (*ImportAnimationResponse) importAnimationRes() {}

// Ref: #/components/schemas/ImportError
type ImportError struct {
	// Dotted JSON-path to the failing field (e.g. "frames[3].pixels[7].x"); empty string when the failure
	// is not field-specific.
	Field string `json:"field"`
	// Human-readable, server-internal-detail-free explanation.
	Reason string `json:"reason"`
}

// GetField returns the value of Field.
func (s *ImportError) GetField() string {
	return s.Field
}

// GetReason returns the value of Reason.
func (s *ImportError) GetReason() string {
	return s.Reason
}

// SetField sets the value of Field.
func (s *ImportError) SetField(val string) {
	s.Field = val
}

// SetReason sets the value of Reason.
func (s *ImportError) SetReason(val string) {
	s.Reason = val
}

func (*ImportError) importAnimationRes() {}

// Ref: #/components/schemas/ListAnimationsResponse
type ListAnimationsResponse struct {
	// List of saved animations for the device, ordered by updated_at descending.
	Animations []SavedAnimation `json:"animations"`
}

// GetAnimations returns the value of Animations.
func (s *ListAnimationsResponse) GetAnimations() []SavedAnimation {
	return s.Animations
}

// SetAnimations sets the value of Animations.
func (s *ListAnimationsResponse) SetAnimations(val []SavedAnimation) {
	s.Animations = val
}

func (*ListAnimationsResponse) listAnimationsRes() {}

// Ref: #/components/schemas/NameConflict
type NameConflict struct {
	ExistingID   uuid.UUID `json:"existing_id"`
	ExistingName string    `json:"existing_name"`
}

// GetExistingID returns the value of ExistingID.
func (s *NameConflict) GetExistingID() uuid.UUID {
	return s.ExistingID
}

// GetExistingName returns the value of ExistingName.
func (s *NameConflict) GetExistingName() string {
	return s.ExistingName
}

// SetExistingID sets the value of ExistingID.
func (s *NameConflict) SetExistingID(val uuid.UUID) {
	s.ExistingID = val
}

// SetExistingName sets the value of ExistingName.
func (s *NameConflict) SetExistingName(val string) {
	s.ExistingName = val
}

func (*NameConflict) importAnimationRes() {}

// NewOptImportAnimationMode returns new OptImportAnimationMode with value set to v.
func NewOptImportAnimationMode(v ImportAnimationMode) OptImportAnimationMode {
	return OptImportAnimationMode{
		Value: v,
		Set:   true,
	}
}

// OptImportAnimationMode is optional ImportAnimationMode.
type OptImportAnimationMode struct {
	Value ImportAnimationMode
	Set   bool
}

// IsSet returns true if OptImportAnimationMode was set.
func (o OptImportAnimationMode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImportAnimationMode) Reset() {
	var v ImportAnimationMode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImportAnimationMode) SetTo(v ImportAnimationMode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImportAnimationMode) Get() (v ImportAnimationMode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImportAnimationMode) Or(d ImportAnimationMode) ImportAnimationMode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPlayback returns new OptNilPlayback with value set to v.
func NewOptNilPlayback(v Playback) OptNilPlayback {
	return OptNilPlayback{
		Value: v,
		Set:   true,
	}
}

// OptNilPlayback is optional nullable Playback.
type OptNilPlayback struct {
	Value Playback
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPlayback was set.
func (o OptNilPlayback) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPlayback) Reset() {
	var v Playback
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPlayback) SetTo(v Playback) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPlayback) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPlayback) SetToNull() {
	o.Set = true
	o.Null = true
	var v Playback
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilPlayback) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPlayback) Get() (v Playback, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPlayback) Or(d Playback) Playback {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPlayback returns new OptPlayback with value set to v.
func NewOptPlayback(v Playback) OptPlayback {
	return OptPlayback{
		Value: v,
		Set:   true,
	}
}

// OptPlayback is optional Playback.
type OptPlayback struct {
	Value Playback
	Set   bool
}

// IsSet returns true if OptPlayback was set.
func (o OptPlayback) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPlayback) Reset() {
	var v Playback
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPlayback) SetTo(v Playback) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPlayback) Get() (v Playback, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPlayback) Or(d Playback) Playback {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PlayAnimationInternalServerError Error

func (*PlayAnimationInternalServerError) playAnimationRes() {}

type PlayAnimationNotFound Error

func (*PlayAnimationNotFound) playAnimationRes() {}

// Ref: #/components/schemas/PlayAnimationRequest
type PlayAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *PlayAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *PlayAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// Ref: #/components/schemas/PlayAnimationResponse
type PlayAnimationResponse struct {
	Message  string   `json:"message"`
	Playback Playback `json:"playback"`
}

// GetMessage returns the value of Message.
func (s *PlayAnimationResponse) GetMessage() string {
	return s.Message
}

// GetPlayback returns the value of Playback.
func (s *PlayAnimationResponse) GetPlayback() Playback {
	return s.Playback
}

// SetMessage sets the value of Message.
func (s *PlayAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetPlayback sets the value of Playback.
func (s *PlayAnimationResponse) SetPlayback(val Playback) {
	s.Playback = val
}

func (*PlayAnimationResponse) playAnimationRes() {}

// Ref: #/components/schemas/Playback
type Playback struct {
	// Saved animation id; absent for unsaved playback.
	AnimationID OptString `json:"animation_id"`
	// Saved animation name; absent for unsaved playback.
	AnimationName OptString `json:"animation_name"`
	// Frames being played; present only for unsaved playback.
	Frames []AnimationFrame `json:"frames"`
}

// GetAnimationID returns the value of AnimationID.
func (s *Playback) GetAnimationID() OptString {
	return s.AnimationID
}

// GetAnimationName returns the value of AnimationName.
func (s *Playback) GetAnimationName() OptString {
	return s.AnimationName
}

// GetFrames returns the value of Frames.
func (s *Playback) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetAnimationID sets the value of AnimationID.
func (s *Playback) SetAnimationID(val OptString) {
	s.AnimationID = val
}

// SetAnimationName sets the value of AnimationName.
func (s *Playback) SetAnimationName(val OptString) {
	s.AnimationName = val
}

// SetFrames sets the value of Frames.
func (s *Playback) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

type PowerOffBadRequest Error

func (*PowerOffBadRequest) powerOffRes() {}

type PowerOffInternalServerError Error

func (*PowerOffInternalServerError) powerOffRes() {}

// PowerOffNoContent is response for PowerOff operation.
type PowerOffNoContent struct{}

func (*PowerOffNoContent) powerOffRes() {}

// Ref: #/components/schemas/PowerOffRequest
type PowerOffRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *PowerOffRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *PowerOffRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

type PowerOnBadRequest Error

func (*PowerOnBadRequest) powerOnRes() {}

type PowerOnInternalServerError Error

func (*PowerOnInternalServerError) powerOnRes() {}

// PowerOnNoContent is response for PowerOn operation.
type PowerOnNoContent struct{}

func (*PowerOnNoContent) powerOnRes() {}

// Ref: #/components/schemas/PowerOnRequest
type PowerOnRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *PowerOnRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *PowerOnRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// Ref: #/components/schemas/RGBPixel
type RGBPixel struct {
	// Red component (0-255).
	R int32 `json:"r"`
	// Green component (0-255).
	G int32 `json:"g"`
	// Blue component (0-255).
	B int32 `json:"b"`
}

// GetR returns the value of R.
func (s *RGBPixel) GetR() int32 {
	return s.R
}

// GetG returns the value of G.
func (s *RGBPixel) GetG() int32 {
	return s.G
}

// GetB returns the value of B.
func (s *RGBPixel) GetB() int32 {
	return s.B
}

// SetR sets the value of R.
func (s *RGBPixel) SetR(val int32) {
	s.R = val
}

// SetG sets the value of G.
func (s *RGBPixel) SetG(val int32) {
	s.G = val
}

// SetB sets the value of B.
func (s *RGBPixel) SetB(val int32) {
	s.B = val
}

type SaveAnimationBadRequest Error

func (*SaveAnimationBadRequest) saveAnimationRes() {}

type SaveAnimationConflict Error

func (*SaveAnimationConflict) saveAnimationRes() {}

type SaveAnimationInternalServerError Error

func (*SaveAnimationInternalServerError) saveAnimationRes() {}

// Ref: #/components/schemas/SaveAnimationRequest
type SaveAnimationRequest struct {
	// Unique device identifier.
	DeviceID string `json:"device_id"`
	// Name for the animation.
	Name string `json:"name"`
	// Array of animation frames to save.
	Frames []AnimationFrame `json:"frames"`
}

// GetDeviceID returns the value of DeviceID.
func (s *SaveAnimationRequest) GetDeviceID() string {
	return s.DeviceID
}

// GetName returns the value of Name.
func (s *SaveAnimationRequest) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *SaveAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetDeviceID sets the value of DeviceID.
func (s *SaveAnimationRequest) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetName sets the value of Name.
func (s *SaveAnimationRequest) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *SaveAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/SaveAnimationResponse
type SaveAnimationResponse struct {
	// UUID of the newly saved animation.
	ID string `json:"id"`
	// Success message.
	Message   string         `json:"message"`
	Animation SavedAnimation `json:"animation"`
}

// GetID returns the value of ID.
func (s *SaveAnimationResponse) GetID() string {
	return s.ID
}

// GetMessage returns the value of Message.
func (s *SaveAnimationResponse) GetMessage() string {
	return s.Message
}

// GetAnimation returns the value of Animation.
func (s *SaveAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetID sets the value of ID.
func (s *SaveAnimationResponse) SetID(val string) {
	s.ID = val
}

// SetMessage sets the value of Message.
func (s *SaveAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetAnimation sets the value of Animation.
func (s *SaveAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*SaveAnimationResponse) saveAnimationRes() {}

// Ref: #/components/schemas/SavedAnimation
type SavedAnimation struct {
	// Unique animation identifier.
	ID string `json:"id"`
	// Unique device identifier this animation is saved for.
	DeviceID string `json:"device_id"`
	// User-provided name for the animation.
	Name string `json:"name"`
	// Array of animation frames.
	Frames []AnimationFrame `json:"frames"`
	// Timestamp when animation was created.
	CreatedAt time.Time `json:"created_at"`
	// Timestamp when animation was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *SavedAnimation) GetID() string {
	return s.ID
}

// GetDeviceID returns the value of DeviceID.
func (s *SavedAnimation) GetDeviceID() string {
	return s.DeviceID
}

// GetName returns the value of Name.
func (s *SavedAnimation) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *SavedAnimation) GetFrames() []AnimationFrame {
	return s.Frames
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SavedAnimation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SavedAnimation) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SavedAnimation) SetID(val string) {
	s.ID = val
}

// SetDeviceID sets the value of DeviceID.
func (s *SavedAnimation) SetDeviceID(val string) {
	s.DeviceID = val
}

// SetName sets the value of Name.
func (s *SavedAnimation) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *SavedAnimation) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SavedAnimation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SavedAnimation) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/SparseAnimation
type SparseAnimation struct {
	// Semver-style major.minor of the wire format. Same major guarantees forward-compatibility (older
	// readers ignore unknown optional fields); a different major may be rejected by older decoders.
	Version string `json:"version"`
	// Human-readable animation name.
	Name string `json:"name"`
	// Matrix width in pixels.
	Width int32 `json:"width"`
	// Matrix height in pixels.
	Height int32 `json:"height"`
	// Sequence of sparse frames; each frame lists only non-black pixels.
	Frames []SparseFrame `json:"frames"`
}

// GetVersion returns the value of Version.
func (s *SparseAnimation) GetVersion() string {
	return s.Version
}

// GetName returns the value of Name.
func (s *SparseAnimation) GetName() string {
	return s.Name
}

// GetWidth returns the value of Width.
func (s *SparseAnimation) GetWidth() int32 {
	return s.Width
}

// GetHeight returns the value of Height.
func (s *SparseAnimation) GetHeight() int32 {
	return s.Height
}

// GetFrames returns the value of Frames.
func (s *SparseAnimation) GetFrames() []SparseFrame {
	return s.Frames
}

// SetVersion sets the value of Version.
func (s *SparseAnimation) SetVersion(val string) {
	s.Version = val
}

// SetName sets the value of Name.
func (s *SparseAnimation) SetName(val string) {
	s.Name = val
}

// SetWidth sets the value of Width.
func (s *SparseAnimation) SetWidth(val int32) {
	s.Width = val
}

// SetHeight sets the value of Height.
func (s *SparseAnimation) SetHeight(val int32) {
	s.Height = val
}

// SetFrames sets the value of Frames.
func (s *SparseAnimation) SetFrames(val []SparseFrame) {
	s.Frames = val
}

func (*SparseAnimation) exportAnimationRes() {}

type SparseFrame []SparsePixel

// Ref: #/components/schemas/SparsePixel
type SparsePixel struct {
	// Zero-based column index of the lit pixel.
	X int32 `json:"x"`
	// Zero-based row index of the lit pixel.
	Y int32 `json:"y"`
	// 24-bit packed RGB color (0xRRGGBB).
	C int32 `json:"c"`
}

// GetX returns the value of X.
func (s *SparsePixel) GetX() int32 {
	return s.X
}

// GetY returns the value of Y.
func (s *SparsePixel) GetY() int32 {
	return s.Y
}

// GetC returns the value of C.
func (s *SparsePixel) GetC() int32 {
	return s.C
}

// SetX sets the value of X.
func (s *SparsePixel) SetX(val int32) {
	s.X = val
}

// SetY sets the value of Y.
func (s *SparsePixel) SetY(val int32) {
	s.Y = val
}

// SetC sets the value of C.
func (s *SparsePixel) SetC(val int32) {
	s.C = val
}

type StartAnimationBadRequest Error

func (*StartAnimationBadRequest) startAnimationRes() {}

type StartAnimationInternalServerError Error

func (*StartAnimationInternalServerError) startAnimationRes() {}

// Ref: #/components/schemas/StartAnimationRequest
type StartAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
	// Array of animation frames to play in sequence.
	Frames []AnimationFrame `json:"frames"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StartAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// GetFrames returns the value of Frames.
func (s *StartAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StartAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// SetFrames sets the value of Frames.
func (s *StartAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/StartAnimationResponse
type StartAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
	// Number of frames in the animation.
	FrameCount int         `json:"frame_count"`
	Playback   OptPlayback `json:"playback"`
}

// GetMessage returns the value of Message.
func (s *StartAnimationResponse) GetMessage() string {
	return s.Message
}

// GetFrameCount returns the value of FrameCount.
func (s *StartAnimationResponse) GetFrameCount() int {
	return s.FrameCount
}

// GetPlayback returns the value of Playback.
func (s *StartAnimationResponse) GetPlayback() OptPlayback {
	return s.Playback
}

// SetMessage sets the value of Message.
func (s *StartAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetFrameCount sets the value of FrameCount.
func (s *StartAnimationResponse) SetFrameCount(val int) {
	s.FrameCount = val
}

// SetPlayback sets the value of Playback.
func (s *StartAnimationResponse) SetPlayback(val OptPlayback) {
	s.Playback = val
}

func (*StartAnimationResponse) startAnimationRes() {}

type StopAnimationBadRequest Error

func (*StopAnimationBadRequest) stopAnimationRes() {}

type StopAnimationInternalServerError Error

func (*StopAnimationInternalServerError) stopAnimationRes() {}

// Ref: #/components/schemas/StopAnimationRequest
type StopAnimationRequest struct {
	// Device location in format yeelight://IP:PORT.
	DeviceLocation string `json:"device_location"`
}

// GetDeviceLocation returns the value of DeviceLocation.
func (s *StopAnimationRequest) GetDeviceLocation() string {
	return s.DeviceLocation
}

// SetDeviceLocation sets the value of DeviceLocation.
func (s *StopAnimationRequest) SetDeviceLocation(val string) {
	s.DeviceLocation = val
}

// Ref: #/components/schemas/StopAnimationResponse
type StopAnimationResponse struct {
	// Success message.
	Message string `json:"message"`
	// Always null after a stop.
	Playback OptNilPlayback `json:"playback"`
}

// GetMessage returns the value of Message.
func (s *StopAnimationResponse) GetMessage() string {
	return s.Message
}

// GetPlayback returns the value of Playback.
func (s *StopAnimationResponse) GetPlayback() OptNilPlayback {
	return s.Playback
}

// SetMessage sets the value of Message.
func (s *StopAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetPlayback sets the value of Playback.
func (s *StopAnimationResponse) SetPlayback(val OptNilPlayback) {
	s.Playback = val
}

func (*StopAnimationResponse) stopAnimationRes() {}

type UpdateAnimationBadRequest Error

func (*UpdateAnimationBadRequest) updateAnimationRes() {}

type UpdateAnimationConflict Error

func (*UpdateAnimationConflict) updateAnimationRes() {}

type UpdateAnimationInternalServerError Error

func (*UpdateAnimationInternalServerError) updateAnimationRes() {}

type UpdateAnimationNotFound Error

func (*UpdateAnimationNotFound) updateAnimationRes() {}

// Ref: #/components/schemas/UpdateAnimationRequest
type UpdateAnimationRequest struct {
	// Updated name for the animation.
	Name string `json:"name"`
	// Updated animation frames.
	Frames []AnimationFrame `json:"frames"`
}

// GetName returns the value of Name.
func (s *UpdateAnimationRequest) GetName() string {
	return s.Name
}

// GetFrames returns the value of Frames.
func (s *UpdateAnimationRequest) GetFrames() []AnimationFrame {
	return s.Frames
}

// SetName sets the value of Name.
func (s *UpdateAnimationRequest) SetName(val string) {
	s.Name = val
}

// SetFrames sets the value of Frames.
func (s *UpdateAnimationRequest) SetFrames(val []AnimationFrame) {
	s.Frames = val
}

// Ref: #/components/schemas/UpdateAnimationResponse
type UpdateAnimationResponse struct {
	// Success message.
	Message   string         `json:"message"`
	Animation SavedAnimation `json:"animation"`
}

// GetMessage returns the value of Message.
func (s *UpdateAnimationResponse) GetMessage() string {
	return s.Message
}

// GetAnimation returns the value of Animation.
func (s *UpdateAnimationResponse) GetAnimation() SavedAnimation {
	return s.Animation
}

// SetMessage sets the value of Message.
func (s *UpdateAnimationResponse) SetMessage(val string) {
	s.Message = val
}

// SetAnimation sets the value of Animation.
func (s *UpdateAnimationResponse) SetAnimation(val SavedAnimation) {
	s.Animation = val
}

func (*UpdateAnimationResponse) updateAnimationRes() {}
