// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteAnimationOperation OperationName = "DeleteAnimation"
	ExportAnimationOperation OperationName = "ExportAnimation"
	GetAnimationOperation    OperationName = "GetAnimation"
	GetDevicesOperation      OperationName = "GetDevices"
	ImportAnimationOperation OperationName = "ImportAnimation"
	ListAnimationsOperation  OperationName = "ListAnimations"
	PlayAnimationOperation   OperationName = "PlayAnimation"
	PowerOffOperation        OperationName = "PowerOff"
	PowerOnOperation         OperationName = "PowerOn"
	SaveAnimationOperation   OperationName = "SaveAnimation"
	StartAnimationOperation  OperationName = "StartAnimation"
	StopAnimationOperation   OperationName = "StopAnimation"
	UpdateAnimationOperation OperationName = "UpdateAnimation"
)
